import { createIconSetFromIcoMoon } from "react-native-vector-icons";
import icoMoonConfig from "@happy/common/src/assets/selection.json";

export const icons = {
  chat: "chat",
  lightning: "lightning",
  heart: "heart",
  back: "back",
  image: "image",
  camera: "camera",
  location: "location",
  folder: "folder",
  search: "search",
  rightArrow: "right-arrow",
  lock: "lock",
  eye: "eye",
  circleTickFilled: "circle-tick-filled",
  squareTickFilled: "square-tick-filled",
  dancingSolid: "dancing-solid",
  rulerSolid: "ruler-solid",
  microphoneSolid: "microphone-solid",
  penSolid: "pen-solid",
  paintbrushSolid: "paintbrush-solid",
  videoPlayer: "video-player",
  paletteSolid: "palette-solid",
  compassSolid: "compass-solid",
  shuttle: "shuttle",
  yoga: "yoga",
  cricket: "cricket",
  gym: "gym",
  basketball: "basketball",
  running: "running",
  football: "football",
  tennis: "tennis",
  clapperBoard: "clapper-board",
  bookReader: "book-reader",
  cookie: "cookie",
  diceSolid: "dice-solid",
  filmSolid: "film-solid",
  gamepadSolid: "gamepad-solid",
  musicSolid: "music-solid",
  pan: "pan",
  plantSolid: "plant-solid",
  tentSolid: "tent-solid",
  turtleSolid: "turtle-solid",
  beachSolid: "umbrella-beach-solid",
  whiskeySolid: "whiskey-glass-solid",
  wineSolid: "wine-glass-solid",
  martiniSolid: "martini-glass-solid",
  mountainSolid: "mountain-solid",
  mugHotSolid: "mug-hot-solid",
  skiingSolid: "skiing-solid",
  fishing: "fishing",
  pizzaSliceSolid: "pizza-slice-solid",
  roadSolid: "road-solid",
  backpack: "backpack",
  spaSolid: "spa-solid",
  catSolid: "cat-solid",
  citySolid: "city-solid",
  dogSolid: "dog-solid",
  doveSolid: "dove-solid",
  earthSolid: "earth-solid",
  fishSolid: "fish-solid",
  beerSolid: "beer-solid",
  addSolid: "add-solid",
  crossSolid: "cross-solid",
};

export const Icon = createIconSetFromIcoMoon(icoMoonConfig);
